#!/usr/bin/env bash

# Transfers a file from our client to a server

# Variables
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
brown='\e[0;33m'  # Escape sequence for brown color (optional)
reset='\033[0m'   # Escape sequence to reset color (optional)
file="$1"
ip="$2"
user="ubuntu"
key="~/.ssh/id_rsa"

if [ $# -eq 2 ]; then
  scp -i "$key" -o StrictHostKeyChecking=no "$path/$file" "$user"@"$ip":/home/"$user"/
else
  echo -e "${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
  echo "Usage: $filename PATH_TO_FILE IP [USERNAME] [PATH_TO_SSH_KEY]"
fi

